kumuluzee:
  datasources:
    - jndi-name: jdbc/ExternalDS
      connection-url: jdbc:postgresql://34.154.233.200:5432/external
      username: postgres
      password: postgres
      max-pool-size: 20